# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Root workspace (bun/npm) dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"

  # Workspace packages
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/packages/http"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/packages/graphql"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/packages/logger"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/packages/orm"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/packages/platform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"

  # Example applications
  - package-ecosystem: "npm"
    directory: "/examples/basic-http"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/examples/basic-graphql"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/examples/federation-gateway"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/examples/federated-graphql"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"

  - package-ecosystem: "npm"
    directory: "/examples/mongo-orm"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
