import { toValidPackageName } from '../utils/package-name';
import type { TemplateFile } from './project-template';

export interface NextTemplateContext {
  appName: string;
  directory: string;
  packageName?: string;
  bunVersion: string;
}

const createPackageJson = (ctx: NextTemplateContext): string =>
  `${JSON.stringify(
    {
      name: ctx.packageName ?? toValidPackageName(ctx.appName),
      version: '0.0.1',
      private: true,
      type: 'module',
      packageManager: `bun@${ctx.bunVersion}`,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      dependencies: {
        next: '^14.2.5',
        react: '^18.3.1',
        'react-dom': '^18.3.1',
      },
      devDependencies: {
        '@types/node': '^20.14.9',
        '@types/react': '^18.3.3',
        '@types/react-dom': '^18.3.0',
        eslint: '^9.4.0',
        'eslint-config-next': '^14.2.5',
        typescript: '^5.5.2',
      },
    },
    null,
    2,
  )}\n`;

const tsconfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const nextEnv = `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
`;

const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`;

const layoutTsx = `import './globals.css';
import type { ReactNode } from 'react';

export const metadata = {
  title: 'Nael + Next',
  description: 'Next.js frontend generated by the Nael CLI',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

const pageTsx = `import Link from 'next/link';

export default function Home() {
  return (
    <main style={{ fontFamily: 'Inter, system-ui, sans-serif', padding: '2rem' }}>
      <p style={{ fontSize: '0.95rem', color: '#475569' }}>Welcome to</p>
      <h1 style={{ fontSize: '2.25rem', margin: '0.25rem 0 0.75rem' }}>Nael + Next.js</h1>
      <p style={{ color: '#475569', maxWidth: '42rem', lineHeight: 1.6 }}>
        This Next.js app was generated alongside your Nael backend. Wire it to your API under
        <code style={{ background: '#f8fafc', padding: '0.1rem 0.25rem', marginLeft: '0.35rem' }}>/api</code>
        and start building.
      </p>
      <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem' }}>
        <Link
          href="https://nextjs.org/docs"
          style={{ padding: '0.75rem 1rem', borderRadius: '0.5rem', background: '#0f172a', color: '#fff' }}
        >
          Next.js Docs
        </Link>
        <Link
          href="https://github.com/nizulzaim/nl-framework"
          style={{
            padding: '0.75rem 1rem',
            borderRadius: '0.5rem',
            background: '#e2e8f0',
            color: '#0f172a',
            textDecoration: 'none',
          }}
        >
          Nael Framework
        </Link>
      </div>
    </main>
  );
}
`;

const globalsCss = `:root {
  color-scheme: light;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  background: #f8fafc;
  color: #0f172a;
  font-family: 'Inter', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
`;

const gitignore = `.next
node_modules
.env
dist
`;

export const createNextTemplate = (ctx: NextTemplateContext): TemplateFile[] => [
  { path: 'package.json', contents: createPackageJson(ctx) },
  { path: 'tsconfig.json', contents: tsconfig },
  { path: 'next-env.d.ts', contents: nextEnv },
  { path: 'next.config.mjs', contents: nextConfig },
  { path: '.gitignore', contents: gitignore },
  { path: 'app/layout.tsx', contents: layoutTsx },
  { path: 'app/page.tsx', contents: pageTsx },
  { path: 'app/globals.css', contents: globalsCss },
];
