app:
  name: Auth HTTP Example
  defaultUsers:
    - email: admin@example.com
      password: changeme
      roles:
        - admin
server:
  host: 127.0.0.1
  port: 4100
database:
  uri: mongodb://127.0.0.1:27017/nl-framework-auth-example
  dbName: nl-framework-auth-example
auth:
  sessionTtlMs: 3600000
