app:
  name: Better Auth HTTP Example
server:
  host: 127.0.0.1
  port: 4100
auth:
  baseUrl: http://127.0.0.1:4100
  secret: justanotherpassword
  routePrefix: /api/auth
mongo:
  uri: mongodb://127.0.0.1:27017/nl-framework-auth-example
  db: nl-framework-auth-example
