name: PR Build & Check
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  BUN_VERSION: 1.1.22
  CI: true

jobs:
  build-packages:
    name: Build packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build workspace packages
        run: bun run scripts/build-all.ts

  check-examples:
    name: Type-check examples
    runs-on: ubuntu-latest
    needs: build-packages
    strategy:
      fail-fast: false
      matrix:
        example:
          - basic-http
          - basic-graphql
          - federated-graphql
          - federation-gateway
          - mongo-orm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run example check
        run: bun run --cwd examples/${{ matrix.example }} check
